# 1
# string="i like apple"
# r=string.replace("like","love")
# print(r)
# vowels=["a","i","o","e","u"]
# count=0
# for num in r:
#     if num in  vowels:
#         count+=1
# print("count the number of vowels:",count)

# 2
# email=input("enter the email id:")
# if email.endswith("@gmail.com"):
#     print("it is valid email",)
# else:    
#     print(" invalid email",)

# 3
# password =input("enter the password:")
# if(len(password)==8):
#     if("@","$","&","%"):password.isalnum()
#     print ( "valid password")
# else:
#     print("invalid password")
# 4
# id="gowsalya"
# pw=123645
# log_id=input("enter the email id:")
# log_pw=input("enter the password:")
# if log_id==id and log_pw==pw:
#     print("log in sucessfully")
# else:
#     print("log in unsucessfuly" )


# 5
# txt="kids life is very  happy"
# s=txt.isascii()
# print(s)
# print(ord("A"))













